### ISSUE TITLE
Doesn't apply when the game launches?

### ISSUE THREAD

**Issue by AkazaRenn** [lmcintyre/TitleEditPlugin#11]
I tried applying the modified title screen, it works if I get into the character selection page and come back. However, if it is a new launch of the game, I'm still seeing the End Walker title. Am I missing any settings, or I'm having too many plugins installed that Title Edit cannot make it before the title screen is loaded, or something else?

**Comment by lmcintyre** [comment]
You need to have the setting enabled to wait for plugins before loading the game. If this setting doesn't work because you have many Penumbra mods and your game hangs too long and XIVLauncher fails to launch the game, there is no solution.

**Comment by AkazaRenn** [comment]
> You need to have the setting enabled to wait for plugins before loading the game. If this setting doesn't work because you have many Penumbra mods and your game hangs too long and XIVLauncher fails to launch the game, there is no solution.

I don't have many mods in Penumbra but I do have a ton of plugins (60)... Would that be the reason?

**Comment by lmcintyre** [comment]
It shouldn't be. Do you have the option enabled to wait for plugins?

**Comment by AkazaRenn** [comment]
> It shouldn't be. Do you have the option enabled to wait for plugins?

In the launcher, I have `Addon Injection Delay` set to 0ms, using `New` option to load Dalamud.

Here's the full log of startup:
```log
17:50:06.550 | INF [PLUGINM] ============= LoadPluginsSync(DrawAvailableSync) START =============
17:50:06.550 | INF [PLUGINM] ============= LoadPluginsSync(DrawAvailableSync) END =============
17:50:06.551 | INF [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) START =============
17:50:06.551 | INF [PLUGINM] Loading plugin Title Edit
17:50:06.551 | INF [PLUGINM] Loading plugin Yes Already
17:50:06.551 | INF [PLUGINM] Loading plugin NoClippy
17:50:06.551 | INF [PLUGINM] Loading plugin Ready Check Helper
17:50:06.551 | INF [PLUGINM] Loading plugin ReAction
17:50:06.551 | INF [PLUGINM] Loading plugin No Tank You
17:50:06.551 | INF [PLUGINM] Loading plugin NotificationMaster
17:50:06.551 | INF [PLUGINM] Loading plugin Simple Tweaks Plugin
17:50:06.551 | INF [PLUGINM] Loading plugin RepairMe
17:50:06.551 | INF [PLUGINM] Loading plugin Remote Party Finder Uploader
17:50:06.551 | INF [PLUGINM] Loading plugin Slice is Right
17:50:06.551 | INF [PLUGINM] Loading plugin Sonar
17:50:06.552 | INF [PLUGINM] Loading plugin PaissaHouse
17:50:06.569 | INF [IME] Enabled!
17:50:06.569 | INF [PLUGINM] Loading plugin Target Furniture
17:50:06.571 | INF [LOCALPLUGIN] Loading NoClippy.dll
17:50:06.574 | INF [LOCALPLUGIN] Loading PixelPerfect.dll
17:50:06.576 | INF [LOCALPLUGIN] Loading RemotePartyFinder.dll
17:50:06.578 | INF [LOCALPLUGIN] Finished loading RemotePartyFinder.dll
17:50:06.578 | INF [PLUGINM] Loading plugin Teleporter
17:50:06.578 | INF [LOCALPLUGIN] Loading MPTickBar.dll
17:50:06.581 | INF [LOCALPLUGIN] Loading RepairMe.dll
17:50:06.583 | INF [LOCALPLUGIN] Loading ReadyCheckHelper.dll
17:50:06.584 | INF [LOCALPLUGIN] Finished loading PixelPerfect.dll
17:50:06.584 | INF [PLUGINM] Loading plugin Tourist
17:50:06.586 | INF [LOCALPLUGIN] Loading SonarPlugin.dll
17:50:06.588 | INF [LOCALPLUGIN] Loading TargetFurniture.dll
17:50:06.589 | INF [LOCALPLUGIN] Finished loading SonarPlugin.dll
17:50:06.589 | INF [PLUGINM] Loading plugin TriadBuddy
17:50:06.589 | INF [LOCALPLUGIN] Finished loading RepairMe.dll
17:50:06.589 | INF [PLUGINM] Loading plugin UnloadErrorFuckOff
17:50:06.590 | INF [LOCALPLUGIN] Loading SliceIsRight.dll
17:50:06.592 | INF [PLUGINM] Loading plugin Where am I again?
17:50:06.594 | INF [LOCALPLUGIN] Finished loading SliceIsRight.dll
17:50:06.594 | INF [PLUGINM] Loading plugin ezWondrousTails
17:50:06.594 | INF [LOCALPLUGIN] Loading autoSweep.dll
17:50:06.597 | INF [LOCALPLUGIN] Loading SimpleTweaksPlugin.dll
17:50:06.599 | INF [LOCALPLUGIN] Loading NotificationMaster.dll
17:50:06.601 | INF [LOCALPLUGIN] Loading NoTankYou.dll
17:50:06.603 | INF [LOCALPLUGIN] Loading YesAlready.dll
17:50:06.605 | INF [LOCALPLUGIN] Loading ReAction.dll
17:50:06.608 | INF [LOCALPLUGIN] Loading TeleporterPlugin.dll
17:50:06.610 | INF [LOCALPLUGIN] Loading Tourist.dll
17:50:06.612 | INF [LOCALPLUGIN] Loading UnloadErrorFuckOff.dll
17:50:06.614 | INF [LOCALPLUGIN] Finished loading UnloadErrorFuckOff.dll
17:50:06.614 | INF [PLUGINM] Loading plugin ezMiniCactpot
17:50:06.615 | INF [LOCALPLUGIN] Loading TriadBuddy.dll
17:50:06.617 | INF [LOCALPLUGIN] Loading WhereAmIAgain.dll
17:50:06.619 | INF [LOCALPLUGIN] Loading WondrousTailsSolver.dll
17:50:06.621 | INF [LOCALPLUGIN] Loading MiniCactpotSolver.dll
17:50:06.621 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Axis12, 12pt, skew=0, weight=0)" has been requested.
17:50:06.630 | INF [LOCALPLUGIN] Finished loading MiniCactpotSolver.dll
17:50:06.660 | INF [LOCALPLUGIN] Finished loading WhereAmIAgain.dll
17:50:06.660 | INF [PLUGINM] Loading plugin XIVSlothCombo
17:50:06.661 | INF [LOCALPLUGIN] Finished loading MPTickBar.dll
17:50:06.661 | INF [PLUGINM] Loading plugin Market Uploader
17:50:06.669 | INF [LOCALPLUGIN] Loading MarketUploader.dll
17:50:06.670 | INF [LOCALPLUGIN] Finished loading TeleporterPlugin.dll
17:50:06.670 | INF [PLUGINM] Loading plugin JustBackup
17:50:06.671 | INF [LOCALPLUGIN] Loading XIVSlothCombo.dll
17:50:06.676 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Axis36, 39pt, skew=0, weight=0)" has been requested.
17:50:06.700 | INF [LOCALPLUGIN] Loading JustBackup.dll
17:50:06.703 | INF [LOCALPLUGIN] Finished loading MarketUploader.dll
17:50:06.703 | INF [PLUGINM] Loading plugin Better Shadows
17:50:06.710 | INF [LOCALPLUGIN] Loading BetterShadows.dll
17:50:06.713 | INF [LOCALPLUGIN] Finished loading TriadBuddy.dll
17:50:06.713 | INF [PLUGINM] Loading plugin Blue Mage Helper
17:50:06.721 | INF [NotificationMaster] ThreadUpdateActivatedState started
17:50:06.722 | INF [LOCALPLUGIN] Loading BlueMageHelper.dll
17:50:06.722 | INF [NotificationMaster] Enabling cutscene ended module
17:50:06.723 | INF [NotificationMaster] Enabling chat message module
17:50:06.724 | INF [NotificationMaster] Enabling cfPop module
17:50:06.724 | INF [NotificationMaster] Enabling loginError module
17:50:06.724 | INF [LOCALPLUGIN] Finished loading NotificationMaster.dll
17:50:06.724 | INF [PLUGINM] Loading plugin Character Panel Refined
17:50:06.737 | INF [LOCALPLUGIN] Loading CharacterPanelRefined.dll
17:50:06.740 | INF [JustBackup] Backup path: C:\OneDrive\Documents\My Games\FINAL FANTASY XIV Backup
Temp folder: C:\Users\Steam\AppData\Local\Temp\JustBackup-1682373006740
Ffxiv config folder: C:\OneDrive\Documents\My Games\FINAL FANTASY XIV - A Realm Reborn
Plugin config folder: C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs
17:50:06.741 | INF [LOCALPLUGIN] Finished loading JustBackup.dll
17:50:06.741 | INF [PLUGINM] Loading plugin Chill Frames
17:50:06.749 | INF [LOCALPLUGIN] Loading ChillFrames.dll
17:50:06.814 | INF [LOCALPLUGIN] Finished loading BlueMageHelper.dll
17:50:06.814 | INF [PLUGINM] Loading plugin Compass
17:50:06.815 | INF [LOCALPLUGIN] Finished loading BetterShadows.dll
17:50:06.815 | INF [PLUGINM] Loading plugin CurrencyAlert
17:50:06.850 | INF [LOCALPLUGIN] Finished loading NoTankYou.dll
17:50:06.850 | INF [LOCALPLUGIN] Loading Compass.dll
17:50:06.850 | INF [PLUGINM] Loading plugin Character Data Sync
17:50:06.850 | INF [LOCALPLUGIN] Loading CurrencyAlert.dll
17:50:06.857 | INF [LOCALPLUGIN] Loading Dalamud.CharacterSync.dll
17:50:06.863 | INF [LOCALPLUGIN] Finished loading ChillFrames.dll
17:50:06.863 | INF [PLUGINM] Loading plugin Wotsit
17:50:06.871 | INF [LOCALPLUGIN] Loading Dalamud.FindAnything.dll
17:50:06.876 | INF [LOCALPLUGIN] Finished loading Compass.dll
17:50:06.876 | INF [PLUGINM] Loading plugin DalamudRepoBrowser
17:50:06.884 | INF [LOCALPLUGIN] Loading DalamudRepoBrowser.dll
17:50:06.884 | ERR [JustBackup] Error copying file C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682280375\FFXIV_CHR00400000025BCE62\CONTROL0.DAT to C:\Users\Steam\AppData\Local\Temp\JustBackup-1682373006740\plugins\Dalamud.CharacterSync\backups\1682280375\FFXIV_CHR00400000025BCE62: The process cannot access the file 'C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682280375\FFXIV_CHR00400000025BCE62\CONTROL0.DAT' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at JustBackup.JustBackup.CopyFile(String file, String dest) in /work/repo/JustBackup/JustBackup.cs:line 276
17:50:06.886 | INF [LOCALPLUGIN] Finished loading CurrencyAlert.dll
17:50:06.886 | INF [PLUGINM] Loading plugin Death Recap
17:50:06.893 | INF [LOCALPLUGIN] Loading DeathRecap.dll
17:50:06.905 | INF [LOCALPLUGIN] Finished loading DalamudRepoBrowser.dll
17:50:06.905 | INF [PLUGINM] Loading plugin Distance
17:50:06.912 | INF [LOCALPLUGIN] Loading Distance.dll
17:50:06.915 | INF [Distance] UIMouseover function signature found at 0x7FF7C891B580.
17:50:06.926 | INF [SonarPlugin.Dalamud] Initializing Sonar
17:50:06.981 | INF [Dalamud.FindAnything] 41 class jobs loaded.
17:50:07.054 | INF [TriadBuddy] Loaded game data for cards:378, npcs:112
17:50:07.055 | INF [PLUGINM] Loading plugin EnemyListDebuffs
17:50:07.060 | INF [LOCALPLUGIN] Loading EnemyListDebuffs.dll
17:50:07.253 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR00400000025BCE62
17:50:07.259 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR00400000026AF1B8
17:50:07.266 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR00400000026AF6DA
17:50:07.272 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR00400000026AF6FC
17:50:07.284 | INF [DryIoc] PlayerTracker initialized
17:50:07.331 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR004000174B513034
17:50:07.331 | INF [DryIoc] Hunt Notifier Initialized
17:50:07.332 | INF [DryIoc] Fate Notifier Initialized
17:50:07.332 | INF [DryIoc] Lumina Data initialized
17:50:07.334 | INF [DryIoc] Sonar Main Overlay Initialized
17:50:07.337 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR004000174B9CCCDE
17:50:07.344 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR004000174BCC2F19
17:50:07.359 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Axis36, 27pt, skew=0, weight=0)" has been requested.
17:50:07.359 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR004000174C0730D6
17:50:07.368 | INF [Dalamud.CharacterSync] C:\Users\Steam\AppData\Roaming\XIVLauncher\pluginConfigs\Dalamud.CharacterSync\backups\1682373007\FFXIV_CHR004000174C25ECBB
17:50:07.372 | INF [Dalamud.CharacterSync] Backup OK!
17:50:07.524 | INF [DryIoc] Sonar Commands Initialized
17:50:07.527 | INF [DryIoc] FateTracker Initialized
17:50:07.527 | INF [DryIoc] MobTracker Initialized
17:50:08.111 | INF [LOCALPLUGIN] Finished loading Dalamud.FindAnything.dll
17:50:08.112 | INF [PLUGINM] Loading plugin EngageTimer
17:50:08.120 | INF [LOCALPLUGIN] Loading EngageTimer.dll
17:50:08.764 | INF [PLUGINM] Loading plugin ezFauxHollows
17:50:08.775 | INF [LOCALPLUGIN] Loading FauxHollowsSolver.dll
17:50:08.776 | INF [LOCALPLUGIN] Finished loading FauxHollowsSolver.dll
17:50:08.776 | INF [PLUGINM] Loading plugin FlashOnTell
17:50:08.781 | INF [LOCALPLUGIN] Loading FlashOnTell.dll
17:50:08.785 | INF [LOCALPLUGIN] Finished loading FlashOnTell.dll
17:50:08.785 | INF [PLUGINM] Loading plugin fps limiter
17:50:08.789 | INF [LOCALPLUGIN] Loading fpslimiter.dll
17:50:08.792 | INF [LOCALPLUGIN] Finished loading fpslimiter.dll
17:50:08.792 | INF [PLUGINM] Loading plugin Instancinator
17:50:08.796 | INF [LOCALPLUGIN] Loading Instancinator.dll
17:50:08.798 | INF [LOCALPLUGIN] Finished loading Instancinator.dll
17:50:08.799 | INF [PLUGINM] Loading plugin Inventory Search Bar
17:50:08.804 | INF [LOCALPLUGIN] Loading InventorySearchBar.dll
17:50:08.868 | INF [PLUGINM] Loading plugin Item Search
17:50:08.868 | INF [JustBackup] Backup complete.
17:50:08.874 | INF [LOCALPLUGIN] Loading ItemSearchPlugin.dll
17:50:08.918 | INF [LOCALPLUGIN] Finished loading ItemSearchPlugin.dll
17:50:08.918 | INF [PLUGINM] Loading plugin Item Vendor Location
17:50:08.925 | INF [LOCALPLUGIN] Loading ItemVendorLocation.dll
17:50:09.947 | INF [Sonar] Sonar is ready
17:50:09.950 | INF [Sonar] Connected to Sonar
17:50:09.960 | INF [PLUGINM] Loading plugin JobBars
17:50:09.969 | INF [LOCALPLUGIN] Loading JobBars.dll
17:50:10.267 | INF [JobBars] ==== INIT ====
17:50:10.750 | INF [PLUGINM] Loading plugin Market board
17:50:10.758 | INF [LOCALPLUGIN] Loading MarketBoardPlugin.dll


======================= intro screen shows up at about here ======================


17:50:21.834 | INF [EnemyListDebuffs] 7FF7C87C2B60
17:50:22.275 | INF [LOCALPLUGIN] Finished loading WondrousTailsSolver.dll
17:50:22.276 | INF [LOCALPLUGIN] Finished loading Dalamud.CharacterSync.dll
17:50:22.277 | INF [LOCALPLUGIN] Finished loading EnemyListDebuffs.dll
17:50:22.279 | INF [LOCALPLUGIN] Finished loading Tourist.dll
17:50:22.279 | INF [LOCALPLUGIN] Finished loading EngageTimer.dll
17:50:22.309 | INF [Distance] Trying to set up Loc for culture "en"
17:50:22.347 | INF [Distance] Downloaded BNpc aggro range data version 2023.03.24.0000.0000-001 (2023032400000000001)
17:50:22.349 | INF [Distance] Wrote BNpc aggro range data to disk: Version 2023.03.24.0000.0000-001 (2023032400000000001)
17:50:22.355 | INF [Distance] Loaded BNpc aggro range data version 2023.03.24.0000.0000-001 (2023032400000000001)
17:50:22.708 | INF [LOCALPLUGIN] Finished loading DeathRecap.dll
17:50:22.709 | INF [LOCALPLUGIN] Finished loading Distance.dll
17:50:22.709 | INF [ReadyCheckHelper] Trying to set up Loc for culture "en"
17:50:22.711 | INF [NoClippy] Loaded module: NoClippy.Modules.AnimationLock
17:50:22.711 | INF [NoClippy] Loaded module: NoClippy.Modules.Logging
17:50:22.713 | INF [LOCALPLUGIN] Finished loading JobBars.dll
17:50:22.713 | INF [LOCALPLUGIN] Finished loading autoSweep.dll
17:50:22.714 | INF [LOCALPLUGIN] Finished loading ReadyCheckHelper.dll
17:50:22.715 | INF [LOCALPLUGIN] Finished loading TargetFurniture.dll
17:50:22.717 | INF [LOCALPLUGIN] Finished loading MarketBoardPlugin.dll
17:50:22.722 | INF [LOCALPLUGIN] Finished loading YesAlready.dll
17:50:22.725 | INF [NoClippy] Loaded module: NoClippy.Modules.QueueThreshold
17:50:22.726 | INF [LOCALPLUGIN] Finished loading XIVSlothCombo.dll
17:50:22.727 | INF [NoClippy] Loaded module: NoClippy.Modules.StatusPrediction
17:50:22.728 | INF [LOCALPLUGIN] Finished loading NoClippy.dll
17:50:22.729 | INF [LOCALPLUGIN] Finished loading CharacterPanelRefined.dll
17:50:22.732 | INF [LOCALPLUGIN] Finished loading InventorySearchBar.dll
17:50:22.754 | INF [SimpleTweaksPlugin] Tweak Blacklist:
17:50:22.754 | INF [SimpleTweaksPlugin] StopCraftingButton
17:50:22.754 | INF [SimpleTweaksPlugin] FixedShadowDistance
17:50:22.754 | INF [SimpleTweaksPlugin] RefreshMarketPrices
17:50:22.754 | INF [SimpleTweaksPlugin] TooltipTweaks
17:50:22.794 | INF [SimpleTweaksPlugin] Enable: Clickable Links in Chat @ Chat Tweaks
17:50:22.795 | INF [SimpleTweaksPlugin] Enable: Disable Chat Movement @ Chat Tweaks
17:50:22.796 | INF [LOCALPLUGIN] Finished loading ReAction.dll
17:50:22.796 | INF [SimpleTweaksPlugin] Enable: Smart AutoScroll @ Chat Tweaks
17:50:22.872 | INF [SimpleTweaksPlugin] Enable: Extra Information for Tooltips @ Tooltip Tweaks
17:50:22.874 | INF [SimpleTweaksPlugin] Enable: Improved Blue Mage Action Tooltips @ Tooltip Tweaks
17:50:22.874 | INF [SimpleTweaksPlugin] Enable: Item Hotkeys @ Tooltip Tweaks
17:50:22.914 | INF [SimpleTweaksPlugin] Enable: Materia Stats @ Tooltip Tweaks
17:50:22.918 | INF [SimpleTweaksPlugin] Enable: Precise Durability @ Tooltip Tweaks
17:50:22.919 | INF [SimpleTweaksPlugin] Enable: Precise Spiritbond @ Tooltip Tweaks
17:50:22.919 | INF [SimpleTweaksPlugin] Enable: Show Desynthesis Skill @ Tooltip Tweaks
17:50:22.921 | INF [SimpleTweaksPlugin] Enable: Show expected food and potion stats @ Tooltip Tweaks
17:50:22.926 | INF [SimpleTweaksPlugin] Payload: RawText - Text: Restores up to 
17:50:22.927 | INF [SimpleTweaksPlugin] Payload: RawText - Text: ??%
17:50:22.927 | INF [SimpleTweaksPlugin] Payload: RawText - Text:  (
17:50:22.927 | INF [SimpleTweaksPlugin] Payload: RawText - Text: ????
17:50:22.927 | INF [SimpleTweaksPlugin] Payload: RawText - Text: )
17:50:22.927 | INF [SimpleTweaksPlugin] Payload: RawText - Text:  of HP (
17:50:22.927 | INF [SimpleTweaksPlugin] Payload: RawText - Text: ????
17:50:22.927 | INF [SimpleTweaksPlugin] Payload: RawText - Text:  points max).
17:50:22.927 | INF [SimpleTweaksPlugin] Enable: Track Faded Orchestrion Rolls @ Tooltip Tweaks
17:50:22.932 | INF [LOCALPLUGIN] Finished loading ItemVendorLocation.dll
17:50:22.999 | INF [websocket-sharp-standard] WebSocket connected
17:50:23.000 | INF [SimpleTweaksPlugin] Enable: Accurate Venture Times @ UI Tweaks
17:50:23.002 | INF [SimpleTweaksPlugin] Enable: Adjust Equipment Positions @ UI Tweaks
17:50:23.050 | INF [SimpleTweaksPlugin] Enable: Adjust Large Cooldown Counter @ UI Tweaks
17:50:23.053 | INF [SimpleTweaksPlugin] Enable: Cast Bar Adjustments @ UI Tweaks
17:50:23.057 | INF [SimpleTweaksPlugin] Enable: Cleaner World Visit Menu @ UI Tweaks
17:50:23.057 | INF [SimpleTweaksPlugin] Enable: Combo Timer @ UI Tweaks
17:50:23.060 | INF [SimpleTweaksPlugin] Enable: Default to max when selling Triple Triad Cards @ UI Tweaks
17:50:23.060 | INF [SimpleTweaksPlugin] Enable: Duplicate Action Presses Between Hotbars @ UI Tweaks
17:50:23.061 | INF [SimpleTweaksPlugin] Enable: Duplicate Keybind Hints Between Hotbars @ UI Tweaks
17:50:23.062 | INF [SimpleTweaksPlugin] Enable: Extended Desynthesis Window @ UI Tweaks
17:50:23.067 | INF [SimpleTweaksPlugin] Enable: Hide Achievements Nearing Completion Notifications @ UI Tweaks
17:50:23.068 | INF [SimpleTweaksPlugin] Enable: Hide Experience Bar at Max Level @ UI Tweaks
17:50:23.069 | INF [SimpleTweaksPlugin] Enable: Improved Crafting Log @ UI Tweaks
17:50:23.071 | INF [SimpleTweaksPlugin] Enable: Item Level in Examine @ UI Tweaks
17:50:23.072 | INF [SimpleTweaksPlugin] Enable: Market Enhancements @ UI Tweaks
17:50:23.078 | INF [SimpleTweaksPlugin] Enable: Minimap Adjustments @ UI Tweaks
17:50:23.082 | INF [SimpleTweaksPlugin] Enable: Reduced Deep Dungeon Info @ UI Tweaks
17:50:23.082 | INF [SimpleTweaksPlugin] Enable: Remove Community Finder @ UI Tweaks
17:50:23.082 | INF [SimpleTweaksPlugin] Enable: Remove Quest Marker Limit @ UI Tweaks
17:50:23.083 | INF [SimpleTweaksPlugin] Enable: Shield on HP Bar @ UI Tweaks
17:50:23.085 | INF [SimpleTweaksPlugin] Enable: Show Experience Percentage @ UI Tweaks
17:50:23.087 | INF [SimpleTweaksPlugin] Enable: Timer on Duty Waiting @ UI Tweaks
17:50:23.111 | INF [LOCALPLUGIN] Finished loading SimpleTweaksPlugin.dll
17:50:23.111 | INF [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) END =============
17:50:23.111 | INF [PLUGINM] Loaded plugins on boot
17:50:23.120 | INF Saved cache to "C:\Users\Steam\AppData\Roaming\XIVLauncher\addon\Hooks\7.5.0.3\cachedSigs\2023.03.24.0000.0000.json"
{ } [ Send ]
```

**Comment by lmcintyre** [comment]
You need to enable this setting in /xlsettings.
![image](https://user-images.githubusercontent.com/6005409/234694870-9af43baa-c9bb-4260-8535-7db0b40b124d.png)

**Comment by AkazaRenn** [comment]
> You need to enable this setting in /xlsettings.
> ![image](https://user-images.githubusercontent.com/6005409/234694870-9af43baa-c9bb-4260-8535-7db0b40b124d.png)
> 

A sorry for that. I did have it turned on but it doesn't seem to be doing what it is supposed to?

**Comment by lmcintyre** [comment]
Unfortunately if Title Edit still doesn't work when this setting is enabled, there is nothing more I can do, it is a Dalamud problem.

**Comment by AkazaRenn** [comment]
> Unfortunately if Title Edit still doesn't work when this setting is enabled, there is nothing more I can do, it is a Dalamud problem.

No problem, still thanks for your help!
